export const DOWNLOAD_URL = 'https://github.com/oiper/desktop/releases/latest'
export const GITHUB_REPO = 'https://github.com/oiper/desktop'
export const DOCS_URL = '/docs'
export const RESOURCES_URL = '/resources'
export const CHANGELOG_URL = '/resources/changelog'
export const PRIVACY_POLICY_URL = '/resources/privacy-policy'
export const TERMS_OF_SERVICE_URL = '/resources/terms-of-service'

export const HOME = '/'

export const ANCHOR_FEATURES = '#features'
export const ANCHOR_PERFORMANCE = '#performance'
export const ANCHOR_PRIVACY = '#privacy'
export const ANCHOR_LANGUAGES = '#languages'
export const ANCHOR_TESTIMONIALS = '#testimonials'
export const ANCHOR_PRICING = '#pricing'
